version: '3.4'

services:
  mlflow101:
    image: mlflow101
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m test "]
    ports:
      - 5678:5678
